### ISSUE TITLE
wq，加班信息统计时长出错

### ISSUE THREAD

**Issue by Lighted** [remotesc2/EveryShow#12]
![image](https://cloud.githubusercontent.com/assets/3888988/8819620/6a34b096-3080-11e5-8909-35325a3b32b5.png)

**Comment by remotesc2** [comment]
跟视图统计有关，@kunhour

**Comment by remotesc2** [comment]
在加班录入的时候增加“开始时间”，“结束时间”的判断，防止出现“开始时间”晚于“结束时间”，从而导致“时长”计算失败
